### ISSUE TITLE
Problem with transactions

### ISSUE THREAD

**Issue by tongokongo** [NemProject/nem-py#1]
python nickel.py transfer 3029c55412442244defb01deef360db9b6ddf4779479e1436e67028dc44ca5f7 TDGIMREMR5NSRFUOMPI5OOHLDATCABNPC5ID2SVA 1000000

Having problem with this request, while using testnet account:
![image](https://user-images.githubusercontent.com/29152385/32347630-75fce332-bfce-11e7-885a-28a5924e7b11.png)
There is another problem using mainnet account:
![image](https://user-images.githubusercontent.com/29152385/32347699-ba3c0ac8-bfce-11e7-8190-18a721196aa7.png)

Gimer, could you help me, what am I doing wrong?

**Comment by tongokongo** [comment]
What about this one? Address exists, I have funds, btw, it's not 1 000 000 XEM, it's 1 XEM. Even with sending 1 from real account with thousands XEMs, still getting "Failure_Insufficient_Balance". 

python nickel.py transfer 3f7794da6348de209d80dc5af59dcd26c21b2ecdcb94829055e4f88e450c670a NDZTPA7AUVVDAO2SXQ77I3V4ZSLETVSPF7CTRROE 1
 [+] PREPARING TRANSACTION
 [!] prepare failed:
{
  "status": 400,
  "timeStamp": 82069431,
  "message": "FAILURE_INSUFFICIENT_BALANCE",
  "error": "Bad Request"
}

**Comment by ikeonet1** [comment]
This request is using the mainnet. Is your setup pointed to use mainnet in your config? If you're still on testnet, it won't find it still.

**Comment by ikeonet1** [comment]
Is this still an issue? If not, please close.
